name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.0.4
        with:
          ACCESS_TOKEN: ${{ secrets.ACTIONS_CI }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build